<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="10" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="DummySuite" duration-ms="122" started-at="2017-07-12T10:21:09Z" finished-at="2017-07-12T10:21:09Z">
    <groups>
    </groups>
    <test name="DummyTest" duration-ms="122" started-at="2017-07-12T10:21:09Z" finished-at="2017-07-12T10:21:09Z">
      <class name="tests.TestClass1">
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass1@ea4a92b]" name="createSoftAssert" is-config="true" duration-ms="83" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass1.TempTest5()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass1@ea4a92b]" name="createSoftAssert" is-config="true" duration-ms="85" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass1.TempTest1()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass1@ea4a92b]" name="createSoftAssert" is-config="true" duration-ms="79" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass1.TempTest2() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass1@ea4a92b]" name="createSoftAssert" is-config="true" duration-ms="28" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass1.TempTest3() throws java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
        <test-method status="FAIL" signature="TempTest3()[pri:0, instance:tests.TestClass1@ea4a92b]" name="TempTest3" duration-ms="31" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [3] but found [4]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [3] but found [4]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at assertions.MyAssertion.assertAll(MyAssertion.java:11)
	at tests.TestClass1.TempTest3(TestClass1.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest3 -->
        <test-method status="FAIL" signature="TempTest4()[pri:0, instance:tests.TestClass1@ea4a92b]" name="TempTest4" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [4] but found [5]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [4] but found [5]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at assertions.MyAssertion.assertAll(MyAssertion.java:11)
	at tests.TestClass1.TempTest4(TestClass1.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest4 -->
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass1@ea4a92b]" name="createSoftAssert" is-config="true" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass1.TempTest4()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
        <test-method status="PASS" signature="TempTest2()[pri:0, instance:tests.TestClass1@ea4a92b]" name="TempTest2" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest2 -->
        <test-method status="PASS" signature="TempTest5()[pri:0, instance:tests.TestClass1@ea4a92b]" name="TempTest5" duration-ms="1" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest5 -->
        <test-method status="PASS" signature="TempTest1()[pri:0, instance:tests.TestClass1@ea4a92b]" name="TempTest1" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest1 -->
      </class> <!-- tests.TestClass1 -->
      <class name="tests.TestClass2">
        <test-method status="PASS" signature="TempTest10()[pri:0, instance:tests.TestClass2@3c5a99da]" name="TempTest10" duration-ms="1" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest10 -->
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass2@3c5a99da]" name="createSoftAssert" is-config="true" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass2.TempTest10()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass2@3c5a99da]" name="createSoftAssert" is-config="true" duration-ms="1" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass2.TempTest6()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
        <test-method status="PASS" signature="TempTest6()[pri:0, instance:tests.TestClass2@3c5a99da]" name="TempTest6" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest6 -->
        <test-method status="PASS" signature="TempTest7()[pri:0, instance:tests.TestClass2@3c5a99da]" name="TempTest7" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest7 -->
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass2@3c5a99da]" name="createSoftAssert" is-config="true" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass2.TempTest7()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
        <test-method status="FAIL" signature="TempTest8()[pri:0, instance:tests.TestClass2@3c5a99da]" name="TempTest8" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [8] but found [9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [8] but found [9]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at assertions.MyAssertion.assertAll(MyAssertion.java:11)
	at tests.TestClass2.TempTest8(TestClass2.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest8 -->
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass2@3c5a99da]" name="createSoftAssert" is-config="true" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass2.TempTest8()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
        <test-method status="FAIL" signature="TempTest9()[pri:0, instance:tests.TestClass2@3c5a99da]" name="TempTest9" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	expected [9] but found [10]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [9] but found [10]
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at assertions.MyAssertion.assertAll(MyAssertion.java:11)
	at tests.TestClass2.TempTest9(TestClass2.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TempTest9 -->
        <test-method status="PASS" signature="createSoftAssert(java.lang.reflect.Method)[pri:0, instance:tests.TestClass2@3c5a99da]" name="createSoftAssert" is-config="true" duration-ms="0" started-at="2017-07-12T15:51:09Z" finished-at="2017-07-12T15:51:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void tests.TestClass2.TempTest9()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createSoftAssert -->
      </class> <!-- tests.TestClass2 -->
    </test> <!-- DummyTest -->
  </suite> <!-- DummySuite -->
</testng-results>
